# For documentation on how to configure this file,
# see diesel.rs/guides/configuring-diesel-cli

[migrations_directory]
dir = "src/database/migrations/"

[print_schema]
file = "src/database/schema.rs"